# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pubsub.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cpubsub.proto\x12\x06\x63ommon\x1a\x19google/protobuf/any.proto\"\x11\n\x0fRegisterRequest\"%\n\x10RegisterResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\"!\n\rListenRequest\x12\x10\n\x08topic_id\x18\x02 \x03(\x05\".\n\x0eListenResponse\x12\x1c\n\x05topic\x18\x02 \x01(\x0b\x32\r.common.Topic\"/\n\x0f\x44ispatchRequest\x12\x1c\n\x05topic\x18\x02 \x01(\x0b\x32\r.common.Topic\"\x12\n\x10\x44ispatchResponse\"\xbc\x01\n\x05Topic\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12-\n\rmessage_value\x18\n \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\x16\n\x0cstring_value\x18\x0b \x01(\tH\x00\x12\x17\n\rinteger_value\x18\x0c \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\r \x01(\x02H\x00\x12\x15\n\x0b\x62ytes_value\x18\x0e \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta2\xc9\x01\n\x06Pubsub\x12?\n\x08Register\x12\x17.common.RegisterRequest\x1a\x18.common.RegisterResponse\"\x00\x12;\n\x06Listen\x12\x15.common.ListenRequest\x1a\x16.common.ListenResponse\"\x00\x30\x01\x12\x41\n\x08\x44ispatch\x12\x17.common.DispatchRequest\x1a\x18.common.DispatchResponse\"\x00(\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='common.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=68,
)


_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='common.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='common.RegisterResponse.timestamp', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=107,
)


_LISTENREQUEST = _descriptor.Descriptor(
  name='ListenRequest',
  full_name='common.ListenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic_id', full_name='common.ListenRequest.topic_id', index=0,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=142,
)


_LISTENRESPONSE = _descriptor.Descriptor(
  name='ListenResponse',
  full_name='common.ListenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='common.ListenResponse.topic', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=190,
)


_DISPATCHREQUEST = _descriptor.Descriptor(
  name='DispatchRequest',
  full_name='common.DispatchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='common.DispatchRequest.topic', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=239,
)


_DISPATCHRESPONSE = _descriptor.Descriptor(
  name='DispatchResponse',
  full_name='common.DispatchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=259,
)


_TOPIC = _descriptor.Descriptor(
  name='Topic',
  full_name='common.Topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='common.Topic.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='common.Topic.timestamp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_value', full_name='common.Topic.message_value', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='common.Topic.string_value', index=3,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='integer_value', full_name='common.Topic.integer_value', index=4,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='common.Topic.float_value', index=5,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='common.Topic.bytes_value', index=6,
      number=14, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='common.Topic.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=262,
  serialized_end=450,
)

_LISTENRESPONSE.fields_by_name['topic'].message_type = _TOPIC
_DISPATCHREQUEST.fields_by_name['topic'].message_type = _TOPIC
_TOPIC.fields_by_name['message_value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_TOPIC.oneofs_by_name['data'].fields.append(
  _TOPIC.fields_by_name['message_value'])
_TOPIC.fields_by_name['message_value'].containing_oneof = _TOPIC.oneofs_by_name['data']
_TOPIC.oneofs_by_name['data'].fields.append(
  _TOPIC.fields_by_name['string_value'])
_TOPIC.fields_by_name['string_value'].containing_oneof = _TOPIC.oneofs_by_name['data']
_TOPIC.oneofs_by_name['data'].fields.append(
  _TOPIC.fields_by_name['integer_value'])
_TOPIC.fields_by_name['integer_value'].containing_oneof = _TOPIC.oneofs_by_name['data']
_TOPIC.oneofs_by_name['data'].fields.append(
  _TOPIC.fields_by_name['float_value'])
_TOPIC.fields_by_name['float_value'].containing_oneof = _TOPIC.oneofs_by_name['data']
_TOPIC.oneofs_by_name['data'].fields.append(
  _TOPIC.fields_by_name['bytes_value'])
_TOPIC.fields_by_name['bytes_value'].containing_oneof = _TOPIC.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE
DESCRIPTOR.message_types_by_name['ListenRequest'] = _LISTENREQUEST
DESCRIPTOR.message_types_by_name['ListenResponse'] = _LISTENRESPONSE
DESCRIPTOR.message_types_by_name['DispatchRequest'] = _DISPATCHREQUEST
DESCRIPTOR.message_types_by_name['DispatchResponse'] = _DISPATCHRESPONSE
DESCRIPTOR.message_types_by_name['Topic'] = _TOPIC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

ListenRequest = _reflection.GeneratedProtocolMessageType('ListenRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTENREQUEST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.ListenRequest)
  })
_sym_db.RegisterMessage(ListenRequest)

ListenResponse = _reflection.GeneratedProtocolMessageType('ListenResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTENRESPONSE,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.ListenResponse)
  })
_sym_db.RegisterMessage(ListenResponse)

DispatchRequest = _reflection.GeneratedProtocolMessageType('DispatchRequest', (_message.Message,), {
  'DESCRIPTOR' : _DISPATCHREQUEST,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.DispatchRequest)
  })
_sym_db.RegisterMessage(DispatchRequest)

DispatchResponse = _reflection.GeneratedProtocolMessageType('DispatchResponse', (_message.Message,), {
  'DESCRIPTOR' : _DISPATCHRESPONSE,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.DispatchResponse)
  })
_sym_db.RegisterMessage(DispatchResponse)

Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), {
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'pubsub_pb2'
  # @@protoc_insertion_point(class_scope:common.Topic)
  })
_sym_db.RegisterMessage(Topic)



_PUBSUB = _descriptor.ServiceDescriptor(
  name='Pubsub',
  full_name='common.Pubsub',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=453,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='common.Pubsub.Register',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Listen',
    full_name='common.Pubsub.Listen',
    index=1,
    containing_service=None,
    input_type=_LISTENREQUEST,
    output_type=_LISTENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Dispatch',
    full_name='common.Pubsub.Dispatch',
    index=2,
    containing_service=None,
    input_type=_DISPATCHREQUEST,
    output_type=_DISPATCHRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBSUB)

DESCRIPTOR.services_by_name['Pubsub'] = _PUBSUB

# @@protoc_insertion_point(module_scope)
